### ISSUE TITLE
reversed parameters

### ISSUE THREAD

**Issue by Eilons** [nunziati/bert-vs-t5-for-question-answering#3]
in the train_t5 files the current call is:
f1, exact_match = validation_set.evaluate(
            target_encoded, model_predictions_encoded)

however the "model_predictions_encoded" and "target_encoded" are reversed. the correct call should be:
f1, exact_match = validation_set.evaluate(
            model_predictions_encoded, target_encoded)

**Comment by nunziati** [comment]
Thak you for your comment, I confirm that it was an error and I will correct it asap.
However, for a lucky chance, the evaluation functions that we used have an intrinsic simmetry that makes the function usable in both senses obtaining the same performance values :)
